[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

# Long-tail pages: first-hit builds, then cached at CDN
[[redirects]]
  from = "/page/*"
  to = "/.netlify/functions/page-odb"
  status = 200

# R2 assets (HTML fragments, PDFs, images) via proxy
[[redirects]]
  from = "/assets/*"
  to = "/.netlify/functions/r2-proxy"
  status = 200

# API proxy to Replit with failover to Supabase Edge Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy"
  status = 200

# Sitemap served from R2
[[redirects]]
  from = "/sitemap.xml"
  to = "/assets/sitemaps/sitemap.xml"
  status = 200

# Modern clean URL redirects
[[redirects]]
  from = "/hub.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/programs.html"
  to = "/programs/"
  status = 301

[[redirects]]
  from = "/government-services.html"
  to = "/contracts/"
  status = 301

[[redirects]]
  from = "/account.html"
  to = "/students/"
  status = 301

[[redirects]]
  from = "/connect.html"
  to = "/contact/"
  status = 301

# Clean URL routing
[[redirects]]
  from = "/programs/*"
  to = "/programs/index.html"
  status = 200

[[redirects]]
  from = "/contracts/*"
  to = "/contracts/index.html"
  status = 200

[[redirects]]
  from = "/students/*"
  to = "/students/index.html"
  status = 200

[[redirects]]
  from = "/contact/*"
  to = "/contact/index.html"
  status = 200

[[redirects]]
  from = "/about/*"
  to = "/about/index.html"
  status = 200

# Student portal routes
[[redirects]]
  from = "/student-portal"
  to = "/student-portal.html"
  status = 200

[[redirects]]
  from = "/enroll"
  to = "/student-portal.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/student-portal.html"
  status = 200

[[redirects]]
  from = "/certificates"
  to = "/student-portal.html"
  status = 200

# SPA catch-all for React/Vite routing (LAST - only for unmatched routes)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Nightly cron (03:00 UTC) — triggers sitemap generation via repository_dispatch
[[scheduled.functions]]
  name = "sitemap-cron"
  cron = "0 3 * * *"