name: Guard Large Files
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Block files > 50MB and built artifacts
        run: |
          set -e
          TOO_BIG=$(git ls-files -s | awk '{print $4}' | xargs -I{} bash -lc 'if [ -f "{}" ]; then size=$(wc -c < "{}"); if [ $size -gt 50000000 ]; then echo "{} ($size bytes)"; fi; fi' || true)
          if [ -n "$TOO_BIG" ]; then
            echo "The following files exceed 50MB:"; echo "$TOO_BIG"; exit 1; fi
          for p in node_modules dist build out .next sites/*/sitemaps uploads static/uploads; do
            if [ -e "$p" ]; then echo "Forbidden path checked in: $p"; exit 1; fi
          done
